name: C Address Book CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make
    
    - name: Compile project
      run: |
        gcc -Wall -Wextra -pedantic -std=c11 \
            main.c contact.c file.c \
            -o addressbook
        
    - name: Run basic test
      run: |
        ./addressbook --help || true
        echo "Smoke test completed"
